[env:nodemcu]
platform = espressif8266
board = nodemcu
framework = arduino
board_build.ldscript = ld/eagle.flash.4m.custom.ld
board_build.filesystem = littlefs
monitor_speed = 115200
upload_speed = 921600
test_filter = test_common test_embedded
lib_deps =
    xoseperez/EEPROM_Rotate@^0.9.2
    mbed-floatlei/eeprom@0.0.0+sha.b71fbcf5b8e4
    https://github.com/jbanaszczyk/esp8266-iot-framework.git

build_type = release

build_flags =

    -D BEARSSL_SSL_BASIC
    -D HTTPCLIENT_1_1_COMPATIBLE=0
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY_LOW_FLASH
    -D PIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK22x_191122
    -D VTABLES_IN_IRAM

;    -DREBUILD_CONFIG
;    -DCONFIG_PATH=src/configuration.json

;    -DREBUILD_DASHBOARD
;    -DDASHBOARD_PATH=src/dashboard.json

;    -DREBUILD_HTML

;    -DREBUILD_CERTS
    -Dopenssl="C:/Program Files/Git/usr/bin/openssl.exe"
    -DDOMAIN_LIST=google.com,ipgeolocation.io

;    -DDEBUG_ESP_PORT=Serial
;
;    -D_DEBUG_HTTPCLIENT=Serial.printf
;    -D_DEBUG_ESP_CORE
;
