[env:nodemcu]
platform = espressif8266
board = nodemcu
framework = arduino
board_build.ldscript = ld/eagle.flash.4m.custom.ld
board_build.filesystem = littlefs
monitor_speed = 74880
upload_speed = 921600
test_filter = test_common test_embedded
lib_deps =
    https://github.com/arkhipenko/TaskScheduler.git
    https://github.com/jbanaszczyk/esp8266-iot-framework.git

build_type = release

build_flags =
    -D BEARSSL_SSL_BASIC
    -D HTTPCLIENT_1_1_COMPATIBLE=0
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY_LOW_FLASH
    -D PIO_FRAMEWORK_ARDUINO_ESPRESSIF_SDK22x_191122
    -D VTABLES_IN_IRAM

;    -D DEBUG_ESP_PORT=Serial
;    -D DEBUG_ESP_WIFI

    -D _TASK_LTS_POINTER
    -D _TASK_STD_FUNCTION

;    -D DEBUG_EEPROM_ROTATE_PORT=Serial
    -D NO_GLOBAL_EEPROM

    -D DEBUG_IOT_PORT=Serial
;    -D DEBUG_IOT_LEVEL=INFO

    -D DEBUG_SERIAL_COMMANDS=INFO
    -D DEBUG_IOT_WIFI_MANAGER=INFO
    -D DEBUG_IOT_OTA=INFO
    -D DEBUG_IOT_CERT_STORE=INFO
    -D DEBUG_IOT_CONFIG_MANAGER=INFO

    -D DEBUG_IOT_COMMANDS=INFO

;    -D REBUILD_CONFIG
;    -D CONFIG_PATH=src/configuration.json

;    -D REBUILD_DASHBOARD
;    -D DASHBOARD_PATH=src/dashboard.json

;    -D REBUILD_HTML

;    -D REBUILD_CERTS
;    -D openssl="C:/Program Files/Git/usr/bin/openssl.exe"
;    -D DOMAIN_LIST=google.com

; Do not use, because WiFi does not work
;    -D_DEBUG_HTTPCLIENT=Serial.printf
;    -D_DEBUG_ESP_CORE
